"""Initial migration

Revision ID: 04b8e6ffac19
Revises: df3e7cb3f460
Create Date: 2024-09-22 16:33:34.500217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b8e6ffac19'
down_revision: Union[str, None] = 'df3e7cb3f460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_call_logs', sa.Column('country', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_call_logs', 'country')
    # ### end Alembic commands ###
